#!/bin/sh

# Pass in env variable HUGOCONFIG

(
  flock -x 200 || exit 1

  cd /data/web/build/www/
  /usr/bin/hugo --config $HUGOCONFIG --ignoreCache

  rsync -a /data/web/build/www/public/ /data/web/www.aroomintown.com/

) 200>/data/web/build/.deploy.exclusivelock

